@baseUrl=http://localhost:3001
@noteid=678ae795222a645e5fa5dff0
@userid=678adebb64cd520a73b90141

# Get index
GET {{baseUrl}}/

###
# Get all notes
GET {{baseUrl}}/api/notes

###
# Get one note
GET {{baseUrl}}/api/notes/{{noteid}}

###
# Delete one note
DELETE {{baseUrl}}/api/notes/{{noteid}}

###
# Create one note
POST {{baseUrl}}/api/notes
Content-Type: application/json

{
	"content": "i can make notes!",
	"important": true,
	"userId": "{{userid}}"
}

###
# Update one note
PUT {{baseUrl}}/api/notes/{{id}}
Content-Type: application/json

{
	"content": "lol",
	"important": false
}

###
# Get all users
GET {{baseUrl}}/api/users

###
# Create a user
POST {{baseUrl}}/api/users
Content-Type: application/json

{
	"username": "knox131313",
	"name": "knox",
	"password": "fakepassword"
}
