# fly.toml app configuration file generated for fullstackopen-backend-phonebook-maggie on 2025-01-10T17:00:37-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fullstackopen-backend-phonebook-maggie'
primary_region = 'sea'

[env]
PORT = '3000'

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
