@baseUrl=http://localhost:3001
# @baseUrl=https://fullstackopen-backend-phonebook-maggie.fly.dev
@id=6785ad815d24477ffed532d9

# Get info
GET {{baseUrl}}/info

###
# Get all persons
GET {{baseUrl}}/api/persons

###
# Get person by id
GET {{baseUrl}}/api/persons/{{id}}

###
# Delete person by id
DELETE {{baseUrl}}/api/persons/{{id}}

###
# Create a new person
POST {{baseUrl}}/api/persons
Content-Type: application/json

{
	"name": "no",
	"number": "123-123-1234"
}

###
# Update a person
PUT {{baseUrl}}/api/persons/{{id}}
Content-Type: application/json

{
	"name": "Maggie",
	"number": "123-456-7890"
}
