@baseURL=http://localhost:3003
@id=678ac6999f68fc9d684d2f66

# @name get_blogs
GET {{baseURL}}/api/blogs

###
# @name create_blog
POST {{baseURL}}/api/blogs
Content-Type: application/json

{
	"title": "Knox's Cool Blog 3: This Time It's Mine",
	"author": "Knox",
	"url": "http://knox-also-also.example.com",
	"likes": 1
}

###
# @name delete_blog
DELETE {{baseURL}}/api/blogs/{{id}}

###
# @name update_blog
PUT {{baseURL}}/api/blogs/{{id}}
Content-Type: application/json

{
	"title": "Knox's Cool Blog 2: Electric Boogaloo",
	"author": "Knox",
	"url": "http://knox-also.example.com",
	"likes": 1000
}

###
# @name get_users
GET {{baseURL}}/api/users

###
# @name create_user
POST {{baseURL}}/api/users
Content-Type: application/json

{
	"username": "knox13",
	"name": "Knox",
	"password": "supersecret"
}

