@baseURL=http://localhost:3003

# Get all blog 
GET {{baseURL}}/api/blogs

###
# Create blog
POST {{baseURL}}/api/blogs
Content-Type: application/json

{
	"title": "Knox's Cool Blog 4: This is the Final Countdown",
	"author": "Knox",
	"url": "http://knox-also-also-also.example.com",
	"likes": 1
}
